settings:
  static_bias_initialization: false
  initialize_state_from_first_observation: false
  imu_topic: "/lcm_publisher_node/imu"
  map_frame_id : "/odom"
  base_frame_id: "/cheetah/imu"
  pose_topic: "/cheetah/pose"
  state_topic: "/cheetah/inekf_state"
  publish_visualization_markers: true
  visualization_markers_topic: "/cheetah/markers"
  enable_kinematics: true
  flat_ground: false
  kinematics_topic: "/lcm_publisher_node/kinematics"
  contact_topic: "/lcm_publisher_node/contact"
